### ISSUE TITLE
[UX] No scroll to success message after form submit

### ISSUE THREAD

**Issue by wollnyst** [securitywithoutborders/website#51]
Just a small thing: after submitting the volunteer form the scroll position remains where it is. On mobile (iPhone 6s) this is really confusing, since you only see a blank white page

Took me a while to figure out everything was ok. I think I submitted the form a few times.

I'm currently on mobile, so I didn't have any chance to look at the code. But I'm pretty sure I can send a PR in the next days.

**Comment by Tethik** [comment]
You're right. The problem is that the form is actually inside a very tall [iframe](https://github.com/securitywithoutborders/website/blob/master/source/localizable/volunteer.2.html.erb), which doesn't scroll up or resize when the form is submitted. 

Normally I would solve this using JS, but we want to also make sure that everything works for even the most paranoid tor-browser-with-js-disabled-users. As such we try to avoid having anything dependent on JS. You should also be aware that the html/css for the form is kept in another private repo which is currently not publicly available.

If you have any suggestions of a good way to solve this, please let us know. PR would of course be awesome :smile:

**Comment by Prvparamesh** [comment]
There is no Matter in this webpage
